
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_devkitc1]
platform = espressif32
board = esp32s3_devkitc1
framework = arduino, espidf
monitor_speed = 115200
upload_speed = 921600
lib_extra_dirs = lib
lib_deps = 
	olikraus/U8g2
    AsyncTCP
    ESP Async WebServer
	knolleary/PubSubClient
build_type = debug
build_flags = 
	-DGIT_VERSION_NOT_USED
	-DPIO_FRAMEWORK_ARDUINO_SPIFFS_ENABLE
	-Wno-error=format-truncation
	-Wno-error=reorder
	-DCORE_DEBUG_LEVEL=5
	-DASYNC_TCP_RX_BUFFER_SIZE=8192
	-fexceptions
board_build.flash_size = 16MB	
board_build.filesystem = spiffs
board_build.partitions = partitions.csv
monitor_filters = esp32_exception_decoder
extra_scripts = 
	post:uploadfs.py
upload_port =COM3
monitor_port = COM3

